services:
  mysql:
    container_name: api_v2
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_api'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
    expose:
      - '3306:3306'
